// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IAkarIconsLinkChain: typeof import('~icons/akar-icons/link-chain')['default']
    'IFaBrands:github': typeof import('~icons/fa-brands/github')['default']
    'IFaSolid:angleDoubleLeft': typeof import('~icons/fa-solid/angle-double-left')['default']
    'IFaSolid:angleDoubleRight': typeof import('~icons/fa-solid/angle-double-right')['default']
    'IFaSolid:moon': typeof import('~icons/fa-solid/moon')['default']
    'IFaSolid:sun': typeof import('~icons/fa-solid/sun')['default']
    IFaSolidDesktop: typeof import('~icons/fa-solid/desktop')['default']
    IFaSolidMoon: typeof import('~icons/fa-solid/moon')['default']
    IFaSolidSun: typeof import('~icons/fa-solid/sun')['default']
    IIonArrowBackOutline: typeof import('~icons/ion/arrow-back-outline')['default']
    InputA: typeof import('./src/components/input/InputA.vue')['default']
    InputB: typeof import('./src/components/input/InputB.vue')['default']
    InputC: typeof import('./src/components/input/InputC.vue')['default']
    ITwemojiMovieCamera: typeof import('~icons/twemoji/movie-camera')['default']
    IZmdiSmartphoneIphone: typeof import('~icons/zmdi/smartphone-iphone')['default']
  }
}

export { }
