// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'IFaBrands:github': typeof import('~icons/fa-brands/github')['default']
    'IFaSolid:moon': typeof import('~icons/fa-solid/moon')['default']
    'IFaSolid:sun': typeof import('~icons/fa-solid/sun')['default']
    InputA: typeof import('./src/components/input/InputA.vue')['default']
    InputB: typeof import('./src/components/input/InputB.vue')['default']
    InputC: typeof import('./src/components/input/InputC.vue')['default']
  }
}

export { }
