// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'IClarity:collapseCardLine': typeof import('~icons/clarity/collapse-card-line')['default']
    IClaritySettingsLine: typeof import('~icons/clarity/settings-line')['default']
    'IFaSolid:angleDoubleLeft': typeof import('~icons/fa-solid/angle-double-left')['default']
    'IFaSolid:angleDoubleRight': typeof import('~icons/fa-solid/angle-double-right')['default']
    'IFaSolid:moon': typeof import('~icons/fa-solid/moon')['default']
    'IFaSolid:sun': typeof import('~icons/fa-solid/sun')['default']
    IFluentSettings32Regular: typeof import('~icons/fluent/settings32-regular')['default']
    IIonArrowBackOutline: typeof import('~icons/ion/arrow-back-outline')['default']
    'IJam:switchRight': typeof import('~icons/jam/switch-right')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
  }
}
