<template>
  <div class="mb-8 text-2xl">Input</div>
  <div class="mb-5">Input form control with validation:</div>
  <input-a></input-a>
  <div class="mt-12 mb-8 text-xl">Inline label</div>
  <input-b></input-b>
  <div class="mt-12 mb-8 text-xl">Style</div>
  <input-c></input-c>

  <div class="mt-12 mb-8 text-xl">Props</div>
  <props-table :tableData="propsData"></props-table>

  <div class="mt-12 mb-8 text-xl">Events</div>
  <events-table :tableData="eventsData"></events-table>

  <next-bar
    class="mt-24"
    :prev="{ link: '/collapse', text: 'Collapse' }"
    :next="{ link: '/sidebar', text: 'Sidebar' }"
  ></next-bar>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import InputA from "@/components/input/InputA.vue";
import InputB from "@/components/input/InputB.vue";
import InputC from "@/components/input/InputC.vue";
import NextBar from "@/widgets/NextBar.vue";
import PropsTable from "@/widgets/PropsTable.vue";
import EventsTable from "@/widgets/EventsTable.vue";

export default defineComponent({
  components: {
    InputA,
    InputB,
    InputC,
    NextBar,
    PropsTable,
    EventsTable
  },
  setup() {
    const propsData: Array<Record<string, string | boolean>> = [
      {
        prop: "id",
        description: "The id of the widget, it will be autogenerated if not provided",
        type: "string",
        values: "any string",
        default: "",
        required: false,
      },
      {
        prop: "value",
        description: "The initial value of the input",
        type: "string",
        values: "any string",
        default: "",
        required: false,
      },
      {
        prop: "type",
        description: "The input type",
        type: "string",
        values: '<a class="underline" href="https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input">standard input types</a>',
        default: "text",
        required: false,
      },
      {
        prop: "validator",
        description: "The validator function",
        type: "<pre>(value: T) => boolean</pre>",
        values: "a validator function",
        default: "",
        required: false,
      },
      {
        prop: "placeholder",
        description: "The placeholder text",
        type: "string",
        values: "any string",
        default: "",
        required: false,
      },
      {
        prop: "inlineLabel",
        description: "The inline label for inline input",
        type: "string",
        values: "any string",
        default: "",
        required: false,
      },
      {
        prop: "required",
        description: "The html required attribute",
        type: "boolean",
        values: "true, false",
        default: "false",
        required: false,
      },
    ];

    const eventsData: Array<Record<string, string | boolean>> = [
      {
        name: "update:value",
        description: "Event emitted when the input value changes",
        returnType: "string",
      },
      {
        name: "update:isvalid",
        description: "Event emitted when the input value becomes valid",
        returnType: "boolean",
      },
    ];

    return {
      propsData,
      eventsData
    }
  }
});
</script>

<style lang="sass">
#form
  & input
    @apply dark:bg-transparent
</style>

